# Generated by Django 5.1.4 on 2025-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectedcollision",
            name="published_to_mqtt",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this collision has been published via MQTT.",
            ),
        ),
    ]
