# Generated by Django 5.1.4 on 2025-04-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_detectedcollision_published_to_mqtt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransitInformation",
            new_name="VtsSituation",
        ),
    ]
