# Generated by Django 5.1.4 on 2025-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_rename_transitinformation_vtssituation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="busroute",
            options={
                "ordering": ["route_id"],
                "verbose_name": "Bus Route",
                "verbose_name_plural": "Bus Routes",
            },
        ),
        migrations.AddField(
            model_name="busroute",
            name="route_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique identifier for the bus route (e.g., '100', 'TFT:Line:34') from the source data",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
