# Generated by Django 5.1.4 on 2025-04-22 08:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        help_text="Route geometry as a LineString (SRID 4326 WGS84)",
                        srid=4326,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version identifier for this route data (if provided by source)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this route information was last updated/imported",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Route",
                "verbose_name_plural": "Bus Routes",
            },
        ),
        migrations.CreateModel(
            name="TransitInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation_id", models.CharField(max_length=255, unique=True)),
                ("version", models.CharField(max_length=255)),
                (
                    "creation_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("version_time", models.DateTimeField(blank=True, null=True)),
                (
                    "probability_of_occurrence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("severity", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_identification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "validity_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("overall_start_time", models.DateTimeField(blank=True, null=True)),
                ("overall_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Primary point location (SRID 4326 WGS84)",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True,
                        help_text="LineString path from posList (SRID 4326 WGS84)",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("location_description", models.TextField(blank=True, null=True)),
                (
                    "road_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("area_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "transit_service_information",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "transit_service_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pos_list_raw",
                    models.TextField(
                        blank=True,
                        help_text="Raw posList string from XML for reference/debugging",
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("filter_used", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetectedCollision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transit_lon", models.FloatField()),
                ("transit_lat", models.FloatField()),
                (
                    "detection_timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("tolerance_meters", models.IntegerField(default=50)),
                (
                    "bus_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_collisions",
                        to="map.busroute",
                    ),
                ),
                (
                    "transit_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_collisions",
                        to="map.transitinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detected Collision",
                "verbose_name_plural": "Detected Collisions",
                "ordering": ["-detection_timestamp", "transit_information"],
                "unique_together": {("transit_information", "bus_route")},
            },
        ),
    ]
